config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do 
      put :change
    end
  end

  devise_for :users
  get 'pages/home'
  get 'about' => "pages#"

root 'pages#home'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks, dependent: :destroy       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]

  # GET /tasks
  # GET /tasks.json
  def index
    @to_do = current_user.tasks.where(state:"to_do")
    @doing = current_user.tasks.where(state:"doing")
    @done = current_user.tasks.where(state:"done")
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change
    @task.update_attributes(state: params[:state])
    respond_to do |format|
      format.html {redirect_to tasks_path, notice:"Task updated"}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<i class='fa fa-check-square-o'></i>Doet".html_safe, root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "About",  about_path %></li>
        <% if current_user %>
          <li><%= link_to  "Logout", destroy_user_session_path, method: :delete  %></li>
          <li><%= link_to  "Settings", edit_user_registration_path %></li>

        <% else %>
          <li><%= link_to  "Login", new_user_session_path %></li>
        <% end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
<%= yield %>
	
</div>

</body>
</html>

app/views/pages/_partialtest.html.erb
<p>Locavore wayfarers biodiesel, messenger bag bespoke drinking vinegar Banksy tofu gastropub readymade keffiyeh crucifix Thundercats Marfa. Crucifix small batch normcore hoodie, plaid post-ironic XOXO aesthetic Truffaut semiotics. Fanny pack actually beard pour-over cronut. Tattooed umami selfies fashion axe disrupt migas. Pop-up kitsch bespoke, migas 3 wolf moon slow-carb locavore keffiyeh kale chips. Raw denim skateboard kitsch small batch, synth mustache craft beer gentrify cliche polaroid you probably haven't heard of them. High Life quinoa selfies, locavore sustainable irony heirloom XOXO selvage keffiyeh church-key cold-pressed.

Mlkshk meh wolf PBR&B authentic. Scenester cred umami, literally letterpress fap Marfa. Photo booth fashion axe chia single-origin coffee American Apparel. Williamsburg Intelligentsia keffiyeh, Etsy umami asymmetrical deep v readymade Bushwick Portland master cleanse banh mi. Master cleanse roof party mlkshk, PBR&B irony vegan mumblecore next level cray kale chips bespoke flannel tattooed. Cray PBR&B hoodie DIY authentic hella, Brooklyn quinoa fanny pack Carles post-ironic Helvetica. Gluten-free kogi small batch, Marfa paleo letterpress pour-over dreamcatcher.

Tousled raw denim bespoke, taxidermy cold-pressed Blue Bottle seitan. YOLO ethical synth cornhole, brunch blog beard. Pour-over semiotics Bushwick heirloom, sartorial lomo McSweeney's Williamsburg cliche quinoa biodiesel plaid. Odd Future fashion axe gluten-free, narwhal Blue Bottle letterpress iPhone Vice pickled Bushwick wayfarers viral fap. Meditation food truck bitters viral next level, keytar wolf lo-fi Banksy trust fund direct trade raw denim Bushwick sartorial pop-up. IPhone McSweeney's 8-bit Bushwick, beard Vice paleo tofu organic meh readymade umami cardigan post-ironic roof party. Mixtape lomo plaid, raw denim XOXO Neutra four dollar toast salvia.

Selvage seitan Intelligentsia fanny pack Carles. Polaroid Blue Bottle roof party, asymmetrical bicycle rights fanny pack DIY. Tote bag Intelligentsia cornhole, seitan locavore keffiyeh small batch try-hard vinyl four dollar toast post-ironic mustache food truck. Brunch paleo scenester 90's. +1 PBR&B XOXO cronut mustache. Marfa bitters church-key, retro try-hard art party salvia Banksy Helvetica Shoreditch listicle fixie. Slow-carb tilde bitters, normcore distillery PBR viral Wes Anderson banh mi tousled asymmetrical.</p>

app/views/pages/about.html.erb
<h1>test</h1>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1><i class="fa fa-check-square-o"></i>Daniel Soetanto's to-do app</h1>
	<h3>To do list reminders</h3>
	<%= link_to "Sign Up", new_user_registration_path ,  class:"btn btn-primary btn-lg" %>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :state %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr>
	<td><%= task.content %></td>
	<td><%= task.state %></td>
	<td><%= link_to 'Show', task %></td>
	<td><%= link_to 'Edit', edit_task_path(task) %></td>
	<td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% if task.state  != "to_do" %>
	<td><%= link_to "Mark as To Do", change_task_path(task, state: "to_do"), method: :put %></td>
	<% end %>
	<% if task.state != "doing" %>
	<td><%= link_to "Mark as Doing", change_task_path(task, state: "doing"), method: :put %></td>
	<% end %>
	<% if task.state != "done" %>
	<td><%= link_to "Mark as Done", change_task_path(task, state: "done"), method: :put %></td>
	<% end %>
</tr>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>To Do</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @to_do %>
  </tbody>
</table>

<h1>Doing</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @doing %>
  </tbody>
</table>

<h1>Done</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @done %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
  <strong>State</strong>
  <%= @task.state %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>